# Generated by Django 4.0.2 on 2022-02-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testnowtime',
            name='con',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='testnowtime',
            name='idx',
            field=models.CharField(default='', max_length=40),
        ),
    ]
