# Generated by Django 4.0.2 on 2022-02-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_testnowtime_con_testnowtime_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnowtime',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
