# Generated by Django 4.0.2 on 2022-02-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_testnowtime_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testnowtime',
            name='id',
        ),
        migrations.AlterField(
            model_name='testnowtime',
            name='idx',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
