# Generated by Django 4.0.2 on 2022-02-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_testnowtime_id_alter_testnowtime_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anslist',
            fields=[
                ('anstype', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('att', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quelist',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('que1', models.TextField()),
                ('que2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('Seltype', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='testnowtime',
        ),
    ]
