# Generated by Django 4.0.2 on 2022-02-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_anslist_quelist_selector_delete_testnowtime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anslist',
            new_name='Ansmod',
        ),
        migrations.RenameModel(
            old_name='Quelist',
            new_name='Quemod',
        ),
    ]
