# Generated by Django 4.0.2 on 2022-02-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_rename_anslist_ansmod_rename_quelist_quemod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quemod',
            name='name',
        ),
        migrations.AddField(
            model_name='quemod',
            name='Selector',
            field=models.ForeignKey(default='선물', on_delete=django.db.models.deletion.CASCADE, to='mainApp.selector'),
        ),
        migrations.AddField(
            model_name='quemod',
            name='que',
            field=models.TextField(default='선물', primary_key=True, serialize=False),
        ),
    ]
