# Generated by Django 4.0.2 on 2022-02-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_remove_quemod_name_quemod_selector_quemod_que'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quemod',
            name='Selector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quelist', to='mainApp.selector'),
        ),
        migrations.AlterField(
            model_name='quemod',
            name='que',
            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
    ]
