# Generated by Django 4.0.2 on 2022-02-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_quemod_selector_alter_quemod_que'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quemod',
            old_name='Selector',
            new_name='sell',
        ),
    ]
