# Generated by Django 4.0.2 on 2022-02-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_rename_selector_quemod_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quemod',
            name='sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.selector'),
        ),
    ]
