# Generated by Django 4.0.2 on 2022-02-19 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_quemod_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quemod',
            name='sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rename', to='mainApp.selector'),
        ),
    ]
