# Generated by Django 4.0.2 on 2022-02-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_alter_quemod_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quemod',
            name='sell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.selector'),
        ),
    ]
