# Generated by Django 4.0.2 on 2022-02-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_alter_quemod_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selector',
            old_name='Seltype',
            new_name='selid',
        ),
    ]
