# Generated by Django 4.0.2 on 2022-02-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_rename_seltype_selector_selid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('taglist', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ansmod',
        ),
        migrations.DeleteModel(
            name='Quemod',
        ),
        migrations.DeleteModel(
            name='Selector',
        ),
    ]
