# Generated by Django 4.0.2 on 2022-02-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_product_delete_ansmod_delete_quemod_delete_selector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typelist',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
