# Generated by Django 4.0.2 on 2022-02-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_typelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('que', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ans1', models.CharField(max_length=20)),
                ('ans2', models.CharField(max_length=20)),
            ],
        ),
    ]
